/**
 * Define all the constants required in application inside this file and export them
 */

export const MAX_TIMEOUT = 10000; // 1000 = 1sec
//
export const FETCH_USER_DATA = "FETCH_USER_DATA";

// Fetch master Data
export const FETCH_MATER_DATA_SUCCESS = "FETCH_MATER_DATA_SUCCESS";
export const FETCH_MATER_DATA_FAILURE = "FETCH_MATER_DATA_FAILURE";
export const FETCH_MATER_DATA_REQUEST = "FETCH_MATER_DATA_REQUEST";

// COMMAN API CONSTANT
export const API_REQUEST = "API_REQUEST";
export const API_FAILURE = "API_FAILURE";

// AUTH API CONSTANT
export const AUTH_API_REQUEST = "AUTH_API_REQUEST";
export const AUTH_API_FAILURE = "AUTH_API_FAILURE";
export const AUTH_LOGOUT_API_REQUEST = "AUTH_LOGOUT_API_REQUEST";

//Login
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

//LogOut
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

//UPDATE PASSWORD
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";

//Forgot Password
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";

//USER PROFILE VIEW
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";

//Form data
export const UPDATE_FORM_DATA = "UPDATE_FORM_DATA";

// Update User Profile
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";

// SET PROFILE PICTURE

export const SET_PROFILE_PICTURE_SUCCESS = "SET_PROFILE_PICTURE_SUCCESS";

